### ISSUE TITLE
Tag is not listed in package repository

### ISSUE THREAD

**Issue by ccnokes** [titoBouzout/Tag#75]
When I do cmd + shift + p, and select install a package, Tag is not listed in the package repositories that Sublime loads. Yet, the documentation says "don't install manually". This leaves me with a conundrum: how do I get Tag in my Sublime?

**Comment by titoBouzout** [comment]
is probably already installed then

**Comment by ccnokes** [comment]
It's not listed for me when I do "list packages". When I do a search to install it's not listed (I've scrolled through the long list manually). 

![screen shot 2015-01-08 at 4 41 12 pm](https://cloud.githubusercontent.com/assets/1610343/5673132/5a2330ac-9755-11e4-91c4-110646e1ab88.png)

I'm running Sublime 2.0.2 by the way. Any ideas on what's going on?

**Comment by titoBouzout** [comment]
yes read the readme

**Comment by ccnokes** [comment]
I installed Sublime 3 and got it working there. But the readme says I could
get it working via package control 2, which I have installed on Sublime 2
but still no luck there. I think you should include manual install
instructions. Thanks for the prompt albeit crappy help.

**Comment by titoBouzout** [comment]
Crappy help? the first two words says "Sublime Text 3" what you don't understand of 3.
