### ISSUE TITLE
Not working on a custom HTML language

### ISSUE THREAD

**Issue by LeonardoGentile** [titoBouzout/Tag#76]
I've created a custom html language `HTML(Angular).tmLanguage` based on the standard `HTML.tmLanguage`.

The `tag` plugin doesn't work for this type of syntax, even tough I added 
```
    "enable_live_tag_linting_document_types": [
        "", "html", "htm", "php", "tpl", "md", "txt",
        "xhtml", "xml", "rdf", "xul", "svg", "xsd", "xslt",
        "tmTheme", "tmPreferences", "tmLanguage", "sublime-snippet", "HTML(Angular)"
    ]
```

Is there a setting I'm missing or it's just not possible to support custom defined languages? What I've defined it's just html with some extra rules for attributes, nothing special

**Comment by titoBouzout** [comment]
thats for file extensions not syntaxes, which ST version are you using?

**Comment by titoBouzout** [comment]
what thing does not work, it has many features...

**Comment by LeonardoGentile** [comment]
It was not working on ST2 and after installing ST3 doesn't work as well.

The highlight of the matching closing tag doesn't work as well as the close on `/`
I haven't tried the other features so far

**Comment by titoBouzout** [comment]
remove it and then install it again please

**Comment by LeonardoGentile** [comment]
ok, done and restarted, nothing changed. If I change the syntax to plain html it will work

**Comment by titoBouzout** [comment]
ok, ,what is the file name?

**Comment by LeonardoGentile** [comment]
`documentation-list.html`

**Comment by titoBouzout** [comment]
OK, can you please paste the content of the file I'll install your pluing to see whats going on, help me to reproduce the problem

**Comment by LeonardoGentile** [comment]
I see, thank you, the file content is not the issue because the problem affects any html document in which I apply the `HTML(Angular)` syntax. If you need I can share the language definition if it might help (in a couple of hours or so)

**Comment by titoBouzout** [comment]
okei please do Im happy to help, take care

**Comment by LeonardoGentile** [comment]
@titoBouzout [here](https://gist.github.com/LeonardoGentile/8fed261d67fed2bd6deb) you can find the HTML language definition for angular templates, I hope it can help. 

Let me know if can I help you with anything else, thanks

**Comment by titoBouzout** [comment]
Hello, I create new file, set language to HTML(Angular), closing tags works, linting works. CAn you please share the content of the file.

**Comment by LeonardoGentile** [comment]
Ok, thank you. I removed the package `angularjs`,  Linting and closing tag are working but the highlight of  the matching closing tag is still not working. Here's an example
```
<ul class="horizontal" ng-show="type == 'alpha'">
    <li class="first" ng-class="{ active : selectedLetter == 'all' }">
        <a href="#" prevent-default ng-click="filter($test, 'all')" class="listing">ALL</a>
    </li>
    <li ng-repeat="letter in letters" ng-class="{ disabled : !isAvailable(letter), active : selectedLetter == letter, number : $first}">
        <a href="#" prevent-default ng-click="filter($event, letter);" class="listing">
            <span dv-if="letter == '0-9'">0 — 9</span>
            <span dv-if="letter != '0-9'">{{letter}}</span>
        </a>
    </li>
</ul>

```

**Comment by titoBouzout** [comment]
This package does not highlight the closing tag, not the opening tag, that is for https://github.com/facelessuser/BracketHighlighter

**Comment by LeonardoGentile** [comment]
Ops, sorry for that, thanks for your time :+1:

**Comment by titoBouzout** [comment]
no problem! :)
