### ISSUE TITLE
If the tag name contains colon, indent will be not correct

### ISSUE THREAD

**Issue by xjsender** [titoBouzout/Tag#79]
For example, If I have a tag named ``abcd:abcde`` and I have below input.
```html
    <abcd:abcde>
    <
```

If I input slash after the ``<`` in the second line, I will get below result,
```html
    <abcd:abcde>
</abcd:abcde>
```

Actually, I want to get below result,
```html
    <abcd:abcde>
    </abcd:abcde>
```

There are many tags like this in [Salesforce Visualforce Page](http://www.salesforce.com/us/developer/docs/pages/index_Left.htm), can you help me fix this problem?

**Comment by titoBouzout** [comment]
which version of St are you using?

**Comment by xjsender** [comment]
@titoBouzout , I have this problem in ``ST 3063``, ``ST 3059`` or ``ST 3083``.

**Comment by xjsender** [comment]
@titoBouzout , how is going on?

**Comment by xjsender** [comment]
@titoBouzout , thanks.

**Comment by xjsender** [comment]
@titoBouzout , I checked and it worked, thanks for your great help.
